version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments_user
      POSTGRES_PASSWORD: payments_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  migration:
    build: .
    command: >
      sh -c "python3 manage.py makemigrations && 
             python3 manage.py migrate"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A core worker -l INFO
    restart: always
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: celery -A core beat
    restart: always
    volumes:
      - .:/usr/src/app/
    depends_on:
      - celery

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - web

volumes:
  .:
  postgres_data:
  static_volume:
  media_volume:
