# Generated by Django 5.0.6 on 2024-06-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Код восстановления пароля'),
        ),
    ]
